version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: azerty
      MYSQL_DATABASE: izimod_db
    ports:
      - "3306:3306"
    networks:
      - backend
    volumes:
      - mysql_data:/var/lib/mysql

  nestjs:
    build: .
    env_file:
      - .env
    container_name: nestjs_app
    ports:
      - "3405:3405"
    networks:
      - backend
    depends_on:
      - mysql
    environment:
      DATABASE_HOST: mysql_db
      DATABASE_PORT: 3306
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: azerty
      DATABASE_NAME: izimod_db
    cap_add:
      - SYS_TIME             
    volumes:
      - /etc/localtime:/etc/localtime:ro 

networks:
  backend:
    driver: bridge

volumes:
  mysql_data:

